const questions = [
  {
    text: "Gule, orange og gyldne flag i Europa?",
    answers: {
      "tyskland": 78,
      "spanien": 66,
      "sverige": 65,
      "belgien": 45,
      "rumænien": 17,
      "portugal": 17,
      "irland": 11,
      "nordmakedonien": 10,
      "litauen": 8,
      "andorra": 7,
      "ukraine": 6,
      "kroatien": 3,
      "moldova": 3,
      "cypern": 2,
      "bosnien-hercegovina": 1,
      "liechtenstein": 1,
      "san marino": 1,
      "montenegro": 0,
      "serbien": 0,
      "slovenien": 0
    }
  },
  {
    text: "højt fra træets grønne top - ord i julesangen på seks bogstaver eller over?",
    answers: {
      "juleglansen": 73,
      "spillemand": 62,
      "stråler": 60,
      "lystigt": 45,
      "dansen": 38,
      "begynder": 32,
      "grønne": 28,
      "spises": 26,
      "trommen": 26,
      "træets": 22,
      "hænger": 16,
      "traktere": 16,
      "køkkenet": 14,
      "børnlil": 12,
      "julegave": 11,
      "tromme": 11,
      "garnet": 9,
      "længer": 8,
      "fændrik": 7,
      "strammer": 7,
      "barnet": 6,
      "hvorpå": 6,
      "kommer": 5,
      "kvæler": 5,
      "merino": 5,
      "forstår": 4,
      "koster": 4,
      "vinterfrakke": 4,
      "strikke": 3,
      "ønsker": 3,
      "bedstefar": 2,
      "bleven": 2,
      "henrik": 2,
      "propert": 2,
      "ryster": 2,
      "dannebrog": 1,
      "datter": 1,
      "engang": 1,
      "respekt": 1,
      "sparer": 1,
      "allerbedste": 0,
      "blanke": 0,
      "bliver": 0,
      "dejlig": 0,
      "derfor": 0,
      "forsigtig": 0,
      "guldpapir": 0,
      "indenfor": 0,
      "kramme": 0,
      "sikken": 0,
      "skylder": 0,
      "svinger": 0,
      "william": 0
    }
  },
  {
    text: "kageingrediens i gulerodskage, brunsviger og drømmekage fra Brovst ", // ifølge 'Frøken Jensens kogebog' og 'God mad - let at lave'
    answers: {
      "hvedemel": 93,
      "sukker": 79,
      "brun farin": 75,
      "gulerod": 71,
      "smør": 63,
      "æg": 63,
      "kokosmel": 51,
      "mælk": 38,
      "bagepulver": 37,
      "gær": 33,
      "salt": 15,
      "kanel": 13,
      "vand": 10,
      "flormelis": 9,
      "flødeost": 7,
      "natron": 7,
      "vaniljesukker": 7,
      "vanilje": 6,
      "rosiner": 5,
      "hakkede nødder": 4,
      "kardemomme": 4,
      "havregryn": 2,
      "vindruekerneolie": 2,
      "citron": 1,
      "creme fraiche": 0,
      "hasselnøddekerner": 0,
      "ingefær": 0,
      "mandler": 0,
      "nellike": 0,
      "valnøddekerner": 0,
      "yoghurt": 0
    }
  }
];